version: '3.8'

services:
  web:
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ../app:/app
  redis:
    image: "redis:6-alpine"
    ports:
      - "6379:6379"